# Generated by Django 3.1.2 on 2020-10-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201012_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/default_icon.png', null=True, upload_to='images/'),
        ),
    ]
