# Generated by Django 3.1.2 on 2020-10-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201011_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.CharField(default='https://icons-for-free.com/iconfiles/png/512/people+person+profile+user+icon-1320186207447274965.png', max_length=300),
        ),
    ]
